general:
#  optimize: True
#  tuning:
#    alpha: [10, 20, 0.05]
#    ks: [1] #, 3, 5]
#  num_cores: 12
#  parallel: True
#  save_predictions: True
#  save_dist_matrix: False
  folder_results: ./results/knn/enzymes
